var bgLibrary = [
{
"gameId": 31260,
"name": "Agricola",
"image": "https://cf.geekdo-images.com/images/pic259085.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic259085_t.jpg",
"minPlayers": 1,
"maxPlayers": 5,
"playingTime": 150,
"isExpansion": false,
"yearPublished": 2007,
"bggRating": 0,
"averageRating": 8.0404,
"rank": 15,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 2749,
"name": "The American Civil War",
"image": "https://cf.geekdo-images.com/images/pic178849.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic178849_t.jpg",
"minPlayers": 2,
"maxPlayers": 4,
"playingTime": 240,
"isExpansion": false,
"yearPublished": 2001,
"bggRating": 0,
"averageRating": 5.65749,
"rank": 12790,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 74,
"name": "Apples to Apples",
"image": "https://cf.geekdo-images.com/images/pic213515.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic213515_t.jpg",
"minPlayers": 4,
"maxPlayers": 10,
"playingTime": 30,
"isExpansion": false,
"yearPublished": 1999,
"bggRating": 0,
"averageRating": 5.92024,
"rank": 2926,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 15987,
"name": "Arkham Horror",
"image": "https://cf.geekdo-images.com/images/pic175966.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic175966_t.jpg",
"minPlayers": 1,
"maxPlayers": 8,
"playingTime": 360,
"isExpansion": false,
"yearPublished": 2005,
"bggRating": 0,
"averageRating": 7.3306,
"rank": 215,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 6187,
"name": "Avalon",
"image": "https://cf.geekdo-images.com/images/pic184991.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic184991_t.jpg",
"minPlayers": 2,
"maxPlayers": 2,
"playingTime": 45,
"isExpansion": false,
"yearPublished": 2003,
"bggRating": 0,
"averageRating": 5.53255,
"rank": 12915,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 1862,
"name": "Avalon",
"image": "https://cf.geekdo-images.com/images/pic223231.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic223231_t.jpg",
"minPlayers": 3,
"maxPlayers": 6,
"playingTime": 45,
"isExpansion": false,
"yearPublished": 1994,
"bggRating": 0,
"averageRating": 5.18929,
"rank": -1,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 98,
"name": "Axis & Allies",
"image": "https://cf.geekdo-images.com/images/pic24006.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic24006_t.jpg",
"minPlayers": 2,
"maxPlayers": 5,
"playingTime": 180,
"isExpansion": false,
"yearPublished": 1981,
"bggRating": 0,
"averageRating": 6.54582,
"rank": 1174,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 2397,
"name": "Backgammon",
"image": "https://cf.geekdo-images.com/images/pic55221.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic55221_t.jpg",
"minPlayers": 2,
"maxPlayers": 2,
"playingTime": 30,
"isExpansion": false,
"yearPublished": -3000,
"bggRating": 0,
"averageRating": 6.52293,
"rank": 1071,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 163,
"name": "Balderdash",
"image": "https://cf.geekdo-images.com/images/pic40574.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic40574_t.jpg",
"minPlayers": 2,
"maxPlayers": 6,
"playingTime": 60,
"isExpansion": false,
"yearPublished": 1984,
"bggRating": 0,
"averageRating": 6.41168,
"rank": 1467,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 3955,
"name": "BANG!",
"image": "https://cf.geekdo-images.com/images/pic1170986.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic1170986_t.jpg",
"minPlayers": 4,
"maxPlayers": 7,
"playingTime": 40,
"isExpansion": false,
"yearPublished": 2002,
"bggRating": 0,
"averageRating": 6.54662,
"rank": 990,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 9653,
"name": "BANG! Dodge City",
"image": "https://cf.geekdo-images.com/images/pic940210.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic940210_t.jpg",
"minPlayers": 3,
"maxPlayers": 8,
"playingTime": 40,
"isExpansion": true,
"yearPublished": 2004,
"bggRating": 0,
"averageRating": 6.883,
"rank": -1,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 8269,
"name": "BANG! High Noon",
"image": "https://cf.geekdo-images.com/images/pic178050.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic178050_t.jpg",
"minPlayers": 4,
"maxPlayers": 7,
"playingTime": 30,
"isExpansion": true,
"yearPublished": 2003,
"bggRating": 0,
"averageRating": 6.72723,
"rank": -1,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 143741,
"name": "BANG! The Dice Game",
"image": "https://cf.geekdo-images.com/images/pic2909713.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic2909713_t.jpg",
"minPlayers": 3,
"maxPlayers": 8,
"playingTime": 15,
"isExpansion": false,
"yearPublished": 2013,
"bggRating": 0,
"averageRating": 7.02261,
"rank": 451,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 2425,
"name": "Battleship",
"image": "https://cf.geekdo-images.com/images/pic288374.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic288374_t.jpg",
"minPlayers": 2,
"maxPlayers": 2,
"playingTime": 30,
"isExpansion": false,
"yearPublished": 1931,
"bggRating": 0,
"averageRating": 4.55812,
"rank": 14644,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 168435,
"name": "Between Two Cities",
"image": "https://cf.geekdo-images.com/images/pic2326114.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic2326114_t.jpg",
"minPlayers": 1,
"maxPlayers": 7,
"playingTime": 20,
"isExpansion": false,
"yearPublished": 2015,
"bggRating": 0,
"averageRating": 7.10725,
"rank": 472,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 822,
"name": "Carcassonne",
"image": "https://cf.geekdo-images.com/images/pic2337577.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic2337577_t.jpg",
"minPlayers": 2,
"maxPlayers": 5,
"playingTime": 45,
"isExpansion": false,
"yearPublished": 2000,
"bggRating": 0,
"averageRating": 7.43286,
"rank": 131,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 142057,
"name": "Carcassonne Big Box",
"image": "https://cf.geekdo-images.com/images/pic201589.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic201589_t.jpg",
"minPlayers": 2,
"maxPlayers": 5,
"playingTime": 45,
"isExpansion": false,
"yearPublished": 2006,
"bggRating": 0,
"averageRating": 7.59882,
"rank": -1,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 50381,
"name": "Cards Against Humanity",
"image": "https://cf.geekdo-images.com/images/pic2909692.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic2909692_t.jpg",
"minPlayers": 4,
"maxPlayers": 30,
"playingTime": 30,
"isExpansion": false,
"yearPublished": 2009,
"bggRating": 0,
"averageRating": 6.1451,
"rank": 2088,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 111861,
"name": "Cards Against Humanity: First Expansion",
"image": "https://cf.geekdo-images.com/images/pic2006294.png",
"thumbnail": "https://cf.geekdo-images.com/images/pic2006294_t.png",
"minPlayers": 4,
"maxPlayers": 30,
"playingTime": 30,
"isExpansion": true,
"yearPublished": 2011,
"bggRating": 0,
"averageRating": 6.83722,
"rank": -1,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 2807,
"name": "Catan: 5-6 Player Extension",
"image": "https://cf.geekdo-images.com/images/pic2420287.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic2420287_t.jpg",
"minPlayers": 5,
"maxPlayers": 6,
"playingTime": 120,
"isExpansion": true,
"yearPublished": 1996,
"bggRating": 0,
"averageRating": 6.99199,
"rank": -1,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 34691,
"name": "Catan: Traders & Barbarians – 5-6 Player Extension",
"image": "https://cf.geekdo-images.com/images/pic2420318.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic2420318_t.jpg",
"minPlayers": 5,
"maxPlayers": 6,
"playingTime": 90,
"isExpansion": true,
"yearPublished": 2008,
"bggRating": 0,
"averageRating": 6.90066,
"rank": -1,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 103091,
"name": "Catan Histories: Merchants of Europe",
"image": "https://cf.geekdo-images.com/images/pic1421257.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic1421257_t.jpg",
"minPlayers": 3,
"maxPlayers": 4,
"playingTime": 120,
"isExpansion": false,
"yearPublished": 2011,
"bggRating": 0,
"averageRating": 6.80475,
"rank": 2812,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 18602,
"name": "Caylus",
"image": "https://cf.geekdo-images.com/images/pic1638795.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic1638795_t.jpg",
"minPlayers": 2,
"maxPlayers": 5,
"playingTime": 150,
"isExpansion": false,
"yearPublished": 2005,
"bggRating": 0,
"averageRating": 7.84474,
"rank": 41,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 2083,
"name": "Checkers",
"image": "https://cf.geekdo-images.com/images/pic113720.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic113720_t.jpg",
"minPlayers": 2,
"maxPlayers": 2,
"playingTime": 30,
"isExpansion": false,
"yearPublished": 1150,
"bggRating": 0,
"averageRating": 4.85985,
"rank": 14632,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 171,
"name": "Chess",
"image": "https://cf.geekdo-images.com/images/pic260745.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic260745_t.jpg",
"minPlayers": 2,
"maxPlayers": 2,
"playingTime": 60,
"isExpansion": false,
"yearPublished": 1475,
"bggRating": 0,
"averageRating": 7.08886,
"rank": 407,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 2386,
"name": "Chinese Checkers",
"image": "https://cf.geekdo-images.com/images/pic113974.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic113974_t.jpg",
"minPlayers": 2,
"maxPlayers": 6,
"playingTime": 30,
"isExpansion": false,
"yearPublished": 1893,
"bggRating": 0,
"averageRating": 5.08259,
"rank": 14593,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 478,
"name": "Citadels",
"image": "https://cf.geekdo-images.com/images/pic3239104.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic3239104_t.jpg",
"minPlayers": 2,
"maxPlayers": 8,
"playingTime": 60,
"isExpansion": false,
"yearPublished": 2000,
"bggRating": 0,
"averageRating": 7.13124,
"rank": 302,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 205398,
"name": "Citadels",
"image": "https://cf.geekdo-images.com/images/pic3119514.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic3119514_t.jpg",
"minPlayers": 2,
"maxPlayers": 8,
"playingTime": 60,
"isExpansion": false,
"yearPublished": 2016,
"bggRating": 0,
"averageRating": 7.65801,
"rank": 800,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 71,
"name": "Civilization",
"image": "https://cf.geekdo-images.com/images/pic114473.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic114473_t.jpg",
"minPlayers": 2,
"maxPlayers": 7,
"playingTime": 360,
"isExpansion": false,
"yearPublished": 1980,
"bggRating": 0,
"averageRating": 7.52049,
"rank": 197,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 1294,
"name": "Clue",
"image": "https://cf.geekdo-images.com/images/pic884234.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic884234_t.jpg",
"minPlayers": 3,
"maxPlayers": 6,
"playingTime": 45,
"isExpansion": false,
"yearPublished": 1949,
"bggRating": 0,
"averageRating": 5.64581,
"rank": 7705,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 178900,
"name": "Codenames",
"image": "https://cf.geekdo-images.com/images/pic2582929.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic2582929_t.jpg",
"minPlayers": 2,
"maxPlayers": 8,
"playingTime": 15,
"isExpansion": false,
"yearPublished": 2015,
"bggRating": 0,
"averageRating": 7.84217,
"rank": 35,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 198773,
"name": "Codenames: Pictures",
"image": "https://cf.geekdo-images.com/images/pic3476592.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic3476592_t.jpg",
"minPlayers": 2,
"maxPlayers": 8,
"playingTime": 20,
"isExpansion": false,
"yearPublished": 2016,
"bggRating": 0,
"averageRating": 7.50561,
"rank": 168,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 5782,
"name": "Coloretto",
"image": "https://cf.geekdo-images.com/images/pic149765.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic149765_t.jpg",
"minPlayers": 2,
"maxPlayers": 5,
"playingTime": 30,
"isExpansion": false,
"yearPublished": 2003,
"bggRating": 0,
"averageRating": 6.96732,
"rank": 470,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 158899,
"name": "Colt Express",
"image": "https://cf.geekdo-images.com/images/pic2869710.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic2869710_t.jpg",
"minPlayers": 2,
"maxPlayers": 6,
"playingTime": 40,
"isExpansion": false,
"yearPublished": 2014,
"bggRating": 0,
"averageRating": 7.20985,
"rank": 284,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 124361,
"name": "Concordia",
"image": "https://cf.geekdo-images.com/images/pic3453267.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic3453267_t.jpg",
"minPlayers": 2,
"maxPlayers": 5,
"playingTime": 100,
"isExpansion": false,
"yearPublished": 2013,
"bggRating": 0,
"averageRating": 8.03815,
"rank": 27,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 65262,
"name": "Connect 4 (Revised Edition)",
"image": "https://cf.geekdo-images.com/images/pic738020.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic738020_t.jpg",
"minPlayers": 2,
"maxPlayers": 2,
"playingTime": 15,
"isExpansion": false,
"yearPublished": 2008,
"bggRating": 0,
"averageRating": 5.0995,
"rank": 14344,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 2719,
"name": "Connect Four",
"image": "https://cf.geekdo-images.com/images/pic859430.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic859430_t.jpg",
"minPlayers": 2,
"maxPlayers": 2,
"playingTime": 10,
"isExpansion": false,
"yearPublished": 1974,
"bggRating": 0,
"averageRating": 4.82497,
"rank": 14633,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 131357,
"name": "Coup",
"image": "https://cf.geekdo-images.com/images/pic2016054.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic2016054_t.jpg",
"minPlayers": 2,
"maxPlayers": 6,
"playingTime": 15,
"isExpansion": false,
"yearPublished": 2012,
"bggRating": 0,
"averageRating": 7.09947,
"rank": 346,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 891,
"name": "Cranium",
"image": "https://cf.geekdo-images.com/images/pic180029.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic180029_t.jpg",
"minPlayers": 4,
"maxPlayers": 16,
"playingTime": 60,
"isExpansion": false,
"yearPublished": 1998,
"bggRating": 0,
"averageRating": 5.70097,
"rank": 5806,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 483,
"name": "Diplomacy",
"image": "https://cf.geekdo-images.com/images/pic288149.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic288149_t.jpg",
"minPlayers": 2,
"maxPlayers": 7,
"playingTime": 360,
"isExpansion": false,
"yearPublished": 1959,
"bggRating": 0,
"averageRating": 7.06091,
"rank": 482,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 39856,
"name": "Dixit",
"image": "https://cf.geekdo-images.com/images/pic3483909.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic3483909_t.jpg",
"minPlayers": 3,
"maxPlayers": 6,
"playingTime": 30,
"isExpansion": false,
"yearPublished": 2008,
"bggRating": 0,
"averageRating": 7.33874,
"rank": 170,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 36218,
"name": "Dominion",
"image": "https://cf.geekdo-images.com/images/pic394356.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic394356_t.jpg",
"minPlayers": 2,
"maxPlayers": 4,
"playingTime": 30,
"isExpansion": false,
"yearPublished": 2008,
"bggRating": 0,
"averageRating": 7.68151,
"rank": 61,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 2394,
"name": "Dominoes",
"image": "https://cf.geekdo-images.com/images/pic90585.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic90585_t.jpg",
"minPlayers": 2,
"maxPlayers": 10,
"playingTime": 30,
"isExpansion": false,
"yearPublished": 1500,
"bggRating": 0,
"averageRating": 5.4347,
"rank": 14265,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 258,
"name": "Fluxx",
"image": "https://cf.geekdo-images.com/images/pic2405641.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic2405641_t.jpg",
"minPlayers": 2,
"maxPlayers": 6,
"playingTime": 30,
"isExpansion": false,
"yearPublished": 1997,
"bggRating": 0,
"averageRating": 5.69945,
"rank": 6051,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 172,
"name": "For Sale",
"image": "https://cf.geekdo-images.com/images/pic1513085.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic1513085_t.jpg",
"minPlayers": 3,
"maxPlayers": 6,
"playingTime": 20,
"isExpansion": false,
"yearPublished": 1997,
"bggRating": 0,
"averageRating": 7.22092,
"rank": 248,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 99,
"name": "Fortress America",
"image": "https://cf.geekdo-images.com/images/pic100262.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic100262_t.jpg",
"minPlayers": 2,
"maxPlayers": 4,
"playingTime": 180,
"isExpansion": false,
"yearPublished": 1986,
"bggRating": 0,
"averageRating": 6.68931,
"rank": 1267,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 115293,
"name": "Fortress America",
"image": "https://cf.geekdo-images.com/images/pic1180433.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic1180433_t.jpg",
"minPlayers": 2,
"maxPlayers": 4,
"playingTime": 150,
"isExpansion": false,
"yearPublished": 2012,
"bggRating": 0,
"averageRating": 6.88198,
"rank": 1904,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 2921,
"name": "The Game of Life",
"image": "https://cf.geekdo-images.com/images/pic288405.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic288405_t.jpg",
"minPlayers": 2,
"maxPlayers": 6,
"playingTime": 60,
"isExpansion": false,
"yearPublished": 1960,
"bggRating": 0,
"averageRating": 4.15211,
"rank": 14655,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 6472,
"name": "A Game of Thrones (first edition)",
"image": "https://cf.geekdo-images.com/images/pic1222116.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic1222116_t.jpg",
"minPlayers": 3,
"maxPlayers": 5,
"playingTime": 180,
"isExpansion": false,
"yearPublished": 2003,
"bggRating": 0,
"averageRating": 7.27841,
"rank": 294,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 19857,
"name": "Glory to Rome",
"image": "https://cf.geekdo-images.com/images/pic1079512.png",
"thumbnail": "https://cf.geekdo-images.com/images/pic1079512_t.png",
"minPlayers": 2,
"maxPlayers": 5,
"playingTime": 60,
"isExpansion": false,
"yearPublished": 2005,
"bggRating": 0,
"averageRating": 7.4949,
"rank": 137,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 7682,
"name": "Go Fish",
"image": "https://cf.geekdo-images.com/images/pic72857.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic72857_t.jpg",
"minPlayers": 2,
"maxPlayers": 6,
"playingTime": 20,
"isExpansion": false,
"yearPublished": -1,
"bggRating": 0,
"averageRating": 3.57764,
"rank": 14650,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 142992,
"name": "Gravwell: Escape from the 9th Dimension",
"image": "https://cf.geekdo-images.com/images/pic2237646.png",
"thumbnail": "https://cf.geekdo-images.com/images/pic2237646_t.png",
"minPlayers": 1,
"maxPlayers": 4,
"playingTime": 35,
"isExpansion": false,
"yearPublished": 2013,
"bggRating": 0,
"averageRating": 6.98842,
"rank": 812,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 4143,
"name": "Guess Who?",
"image": "https://cf.geekdo-images.com/images/pic335812.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic335812_t.jpg",
"minPlayers": 2,
"maxPlayers": 2,
"playingTime": 20,
"isExpansion": false,
"yearPublished": 1979,
"bggRating": 0,
"averageRating": 4.78547,
"rank": 14631,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 116,
"name": "Guillotine",
"image": "https://cf.geekdo-images.com/images/pic143139.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic143139_t.jpg",
"minPlayers": 2,
"maxPlayers": 5,
"playingTime": 30,
"isExpansion": false,
"yearPublished": 1998,
"bggRating": 0,
"averageRating": 6.53252,
"rank": 981,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 5895,
"name": "Hungry Hungry Hippos",
"image": "https://cf.geekdo-images.com/images/pic152043.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic152043_t.jpg",
"minPlayers": 2,
"maxPlayers": 4,
"playingTime": 10,
"isExpansion": false,
"yearPublished": 1966,
"bggRating": 0,
"averageRating": 4.08445,
"rank": 14646,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 54043,
"name": "Jaipur",
"image": "https://cf.geekdo-images.com/images/pic725500.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic725500_t.jpg",
"minPlayers": 2,
"maxPlayers": 2,
"playingTime": 30,
"isExpansion": false,
"yearPublished": 2009,
"bggRating": 0,
"averageRating": 7.54225,
"rank": 96,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 3699,
"name": "Killer Bunnies and the Quest for the Magic Carrot",
"image": "https://cf.geekdo-images.com/images/pic207282.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic207282_t.jpg",
"minPlayers": 2,
"maxPlayers": 8,
"playingTime": 90,
"isExpansion": false,
"yearPublished": 2002,
"bggRating": 0,
"averageRating": 5.49641,
"rank": 14380,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 160499,
"name": "King of New York",
"image": "https://cf.geekdo-images.com/images/pic2407103.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic2407103_t.jpg",
"minPlayers": 2,
"maxPlayers": 6,
"playingTime": 40,
"isExpansion": false,
"yearPublished": 2014,
"bggRating": 0,
"averageRating": 7.13936,
"rank": 380,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 70323,
"name": "King of Tokyo",
"image": "https://cf.geekdo-images.com/images/pic3043734.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic3043734_t.jpg",
"minPlayers": 2,
"maxPlayers": 6,
"playingTime": 30,
"isExpansion": false,
"yearPublished": 2011,
"bggRating": 0,
"averageRating": 7.28206,
"rank": 198,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 70323,
"name": "King of Tokyo",
"image": "https://cf.geekdo-images.com/images/pic3043734.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic3043734_t.jpg",
"minPlayers": 2,
"maxPlayers": 6,
"playingTime": 30,
"isExpansion": false,
"yearPublished": 2011,
"bggRating": 0,
"averageRating": 7.28206,
"rank": 198,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 20437,
"name": "Lords of Vegas",
"image": "https://cf.geekdo-images.com/images/pic774410.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic774410_t.jpg",
"minPlayers": 2,
"maxPlayers": 4,
"playingTime": 60,
"isExpansion": false,
"yearPublished": 2010,
"bggRating": 0,
"averageRating": 7.32672,
"rank": 336,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 50,
"name": "Lost Cities",
"image": "https://cf.geekdo-images.com/images/pic2606107.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic2606107_t.jpg",
"minPlayers": 2,
"maxPlayers": 2,
"playingTime": 30,
"isExpansion": false,
"yearPublished": 1999,
"bggRating": 0,
"averageRating": 7.14724,
"rank": 290,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 129622,
"name": "Love Letter",
"image": "https://cf.geekdo-images.com/images/pic1401448.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic1401448_t.jpg",
"minPlayers": 2,
"maxPlayers": 4,
"playingTime": 20,
"isExpansion": false,
"yearPublished": 2012,
"bggRating": 0,
"averageRating": 7.29951,
"rank": 185,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 463,
"name": "Magic: The Gathering",
"image": "https://cf.geekdo-images.com/images/pic163749.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic163749_t.jpg",
"minPlayers": 2,
"maxPlayers": 2,
"playingTime": 20,
"isExpansion": false,
"yearPublished": 1993,
"bggRating": 0,
"averageRating": 7.44349,
"rank": 150,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 2093,
"name": "Mahjong",
"image": "https://cf.geekdo-images.com/images/pic43709.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic43709_t.jpg",
"minPlayers": 3,
"maxPlayers": 4,
"playingTime": 120,
"isExpansion": false,
"yearPublished": 1850,
"bggRating": 0,
"averageRating": 7.01917,
"rank": 593,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 156496,
"name": "March of the Ants",
"image": "https://cf.geekdo-images.com/images/pic2004618.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic2004618_t.jpg",
"minPlayers": 1,
"maxPlayers": 5,
"playingTime": 70,
"isExpansion": false,
"yearPublished": 2015,
"bggRating": 0,
"averageRating": 7.19761,
"rank": 1631,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 1406,
"name": "Monopoly",
"image": "https://cf.geekdo-images.com/images/pic3640835.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic3640835_t.jpg",
"minPlayers": 2,
"maxPlayers": 8,
"playingTime": 180,
"isExpansion": false,
"yearPublished": 1933,
"bggRating": 0,
"averageRating": 4.4071,
"rank": 14653,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 7098,
"name": "Monopoly: Deluxe Edition",
"image": "https://cf.geekdo-images.com/images/pic35814.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic35814_t.jpg",
"minPlayers": 2,
"maxPlayers": 10,
"playingTime": 180,
"isExpansion": false,
"yearPublished": 1995,
"bggRating": 0,
"averageRating": 5.27551,
"rank": 14480,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 8041,
"name": "Monopoly: The Lord of the Rings Trilogy Edition",
"image": "https://cf.geekdo-images.com/images/pic32934.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic32934_t.jpg",
"minPlayers": 2,
"maxPlayers": 6,
"playingTime": 60,
"isExpansion": false,
"yearPublished": 2003,
"bggRating": 0,
"averageRating": 5.35366,
"rank": 14333,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 36345,
"name": "Monty Python Fluxx",
"image": "https://cf.geekdo-images.com/images/pic385725.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic385725_t.jpg",
"minPlayers": 2,
"maxPlayers": 6,
"playingTime": 40,
"isExpansion": false,
"yearPublished": 2008,
"bggRating": 0,
"averageRating": 6.07284,
"rank": 2524,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 2679,
"name": "Mouse Trap",
"image": "https://cf.geekdo-images.com/images/pic94317.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic94317_t.jpg",
"minPlayers": 2,
"maxPlayers": 4,
"playingTime": 30,
"isExpansion": false,
"yearPublished": 1963,
"bggRating": 0,
"averageRating": 4.10257,
"rank": 14651,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 160477,
"name": "Onitama",
"image": "https://cf.geekdo-images.com/images/pic2904046.png",
"thumbnail": "https://cf.geekdo-images.com/images/pic2904046_t.png",
"minPlayers": 2,
"maxPlayers": 2,
"playingTime": 30,
"isExpansion": false,
"yearPublished": 2014,
"bggRating": 0,
"averageRating": 7.61171,
"rank": 180,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 3737,
"name": "Operation",
"image": "https://cf.geekdo-images.com/images/pic153389.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic153389_t.jpg",
"minPlayers": 1,
"maxPlayers": 6,
"playingTime": 10,
"isExpansion": false,
"yearPublished": 1965,
"bggRating": 0,
"averageRating": 4.05604,
"rank": 14652,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 56692,
"name": "Parade",
"image": "https://cf.geekdo-images.com/images/pic2239001.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic2239001_t.jpg",
"minPlayers": 2,
"maxPlayers": 6,
"playingTime": 45,
"isExpansion": false,
"yearPublished": 2007,
"bggRating": 0,
"averageRating": 6.93767,
"rank": 673,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 2281,
"name": "Pictionary",
"image": "https://cf.geekdo-images.com/images/pic336863.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic336863_t.jpg",
"minPlayers": 3,
"maxPlayers": 16,
"playingTime": 90,
"isExpansion": false,
"yearPublished": 1985,
"bggRating": 0,
"averageRating": 5.81973,
"rank": 3768,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 2651,
"name": "Power Grid",
"image": "https://cf.geekdo-images.com/images/pic173153.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic173153_t.jpg",
"minPlayers": 2,
"maxPlayers": 6,
"playingTime": 120,
"isExpansion": false,
"yearPublished": 2004,
"bggRating": 0,
"averageRating": 7.92628,
"rank": 23,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 3076,
"name": "Puerto Rico",
"image": "https://cf.geekdo-images.com/images/pic158548.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic158548_t.jpg",
"minPlayers": 2,
"maxPlayers": 5,
"playingTime": 150,
"isExpansion": false,
"yearPublished": 2002,
"bggRating": 0,
"averageRating": 8.07651,
"rank": 14,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 25669,
"name": "Qwirkle",
"image": "https://cf.geekdo-images.com/images/pic309353.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic309353_t.jpg",
"minPlayers": 2,
"maxPlayers": 4,
"playingTime": 45,
"isExpansion": false,
"yearPublished": 2006,
"bggRating": 0,
"averageRating": 6.81178,
"rank": 628,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 128882,
"name": "The Resistance: Avalon",
"image": "https://cf.geekdo-images.com/images/pic1398895.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic1398895_t.jpg",
"minPlayers": 5,
"maxPlayers": 10,
"playingTime": 30,
"isExpansion": false,
"yearPublished": 2012,
"bggRating": 0,
"averageRating": 7.69233,
"rank": 74,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 181,
"name": "Risk",
"image": "https://cf.geekdo-images.com/images/pic2920766.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic2920766_t.jpg",
"minPlayers": 2,
"maxPlayers": 6,
"playingTime": 120,
"isExpansion": false,
"yearPublished": 1959,
"bggRating": 0,
"averageRating": 5.58092,
"rank": 13654,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 105134,
"name": "Risk Legacy",
"image": "https://cf.geekdo-images.com/images/pic1196938.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic1196938_t.jpg",
"minPlayers": 3,
"maxPlayers": 5,
"playingTime": 60,
"isExpansion": false,
"yearPublished": 2011,
"bggRating": 0,
"averageRating": 7.53845,
"rank": 200,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 23010,
"name": "Risk: 40th Anniversary Collector's Edition",
"image": "https://cf.geekdo-images.com/images/pic512832.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic512832_t.jpg",
"minPlayers": 2,
"maxPlayers": 6,
"playingTime": 120,
"isExpansion": false,
"yearPublished": 1999,
"bggRating": 0,
"averageRating": 6.32572,
"rank": 3402,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 320,
"name": "Scrabble",
"image": "https://cf.geekdo-images.com/images/pic404651.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic404651_t.jpg",
"minPlayers": 2,
"maxPlayers": 4,
"playingTime": 90,
"isExpansion": false,
"yearPublished": 1948,
"bggRating": 0,
"averageRating": 6.29703,
"rank": 1446,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 152959,
"name": "The Settlers of Catan: 15th Anniversary Wood Edition",
"image": "https://cf.geekdo-images.com/images/pic1126839.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic1126839_t.jpg",
"minPlayers": 3,
"maxPlayers": 6,
"playingTime": 75,
"isExpansion": false,
"yearPublished": 2008,
"bggRating": 0,
"averageRating": 7.50074,
"rank": -1,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 1269,
"name": "Skip-Bo",
"image": "https://cf.geekdo-images.com/images/pic2440687.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic2440687_t.jpg",
"minPlayers": 2,
"maxPlayers": 6,
"playingTime": 20,
"isExpansion": false,
"yearPublished": 1967,
"bggRating": 0,
"averageRating": 5.35322,
"rank": 14484,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 40692,
"name": "Small World",
"image": "https://cf.geekdo-images.com/images/pic428828.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic428828_t.jpg",
"minPlayers": 2,
"maxPlayers": 5,
"playingTime": 80,
"isExpansion": false,
"yearPublished": 2009,
"bggRating": 0,
"averageRating": 7.34019,
"rank": 162,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 2407,
"name": "Sorry!",
"image": "https://cf.geekdo-images.com/images/pic1187187.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic1187187_t.jpg",
"minPlayers": 2,
"maxPlayers": 4,
"playingTime": 30,
"isExpansion": false,
"yearPublished": 1929,
"bggRating": 0,
"averageRating": 4.49584,
"rank": 14645,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 166384,
"name": "Spyfall",
"image": "https://cf.geekdo-images.com/images/pic2453926.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic2453926_t.jpg",
"minPlayers": 3,
"maxPlayers": 8,
"playingTime": 15,
"isExpansion": false,
"yearPublished": 2014,
"bggRating": 0,
"averageRating": 7.1303,
"rank": 342,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 34635,
"name": "Stone Age",
"image": "https://cf.geekdo-images.com/images/pic1632539.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic1632539_t.jpg",
"minPlayers": 2,
"maxPlayers": 4,
"playingTime": 90,
"isExpansion": false,
"yearPublished": 2008,
"bggRating": 0,
"averageRating": 7.6247,
"rank": 73,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 1917,
"name": "Stratego",
"image": "https://cf.geekdo-images.com/images/pic25644.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic25644_t.jpg",
"minPlayers": 2,
"maxPlayers": 2,
"playingTime": 45,
"isExpansion": false,
"yearPublished": 1944,
"bggRating": 0,
"averageRating": 6.04932,
"rank": 2245,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 40432,
"name": "Stratego (Revised Edition)",
"image": "https://cf.geekdo-images.com/images/pic362170.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic362170_t.jpg",
"minPlayers": 2,
"maxPlayers": 2,
"playingTime": 30,
"isExpansion": false,
"yearPublished": 2008,
"bggRating": 0,
"averageRating": 6.21882,
"rank": 3664,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 139443,
"name": "Superfight",
"image": "https://cf.geekdo-images.com/images/pic2429251.png",
"thumbnail": "https://cf.geekdo-images.com/images/pic2429251_t.png",
"minPlayers": 3,
"maxPlayers": 10,
"playingTime": 30,
"isExpansion": false,
"yearPublished": 2013,
"bggRating": 0,
"averageRating": 6.05181,
"rank": 3634,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 2653,
"name": "Survive: Escape from Atlantis!",
"image": "https://cf.geekdo-images.com/images/pic1300182.png",
"thumbnail": "https://cf.geekdo-images.com/images/pic1300182_t.png",
"minPlayers": 2,
"maxPlayers": 4,
"playingTime": 60,
"isExpansion": false,
"yearPublished": 1982,
"bggRating": 0,
"averageRating": 7.32232,
"rank": 209,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 133473,
"name": "Sushi Go!",
"image": "https://cf.geekdo-images.com/images/pic1900075.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic1900075_t.jpg",
"minPlayers": 2,
"maxPlayers": 5,
"playingTime": 15,
"isExpansion": false,
"yearPublished": 2013,
"bggRating": 0,
"averageRating": 7.13236,
"rank": 318,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 9209,
"name": "Ticket to Ride",
"image": "https://cf.geekdo-images.com/images/pic38668.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic38668_t.jpg",
"minPlayers": 2,
"maxPlayers": 5,
"playingTime": 60,
"isExpansion": false,
"yearPublished": 2004,
"bggRating": 0,
"averageRating": 7.47305,
"rank": 112,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 14996,
"name": "Ticket to Ride: Europe",
"image": "https://cf.geekdo-images.com/images/pic66668.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic66668_t.jpg",
"minPlayers": 2,
"maxPlayers": 5,
"playingTime": 60,
"isExpansion": false,
"yearPublished": 2005,
"bggRating": 0,
"averageRating": 7.5843,
"rank": 85,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 163967,
"name": "Tiny Epic Galaxies",
"image": "https://cf.geekdo-images.com/images/pic2349732.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic2349732_t.jpg",
"minPlayers": 1,
"maxPlayers": 5,
"playingTime": 60,
"isExpansion": false,
"yearPublished": 2015,
"bggRating": 0,
"averageRating": 7.41528,
"rank": 221,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 123540,
"name": "Tokaido",
"image": "https://cf.geekdo-images.com/images/pic3747956.png",
"thumbnail": "https://cf.geekdo-images.com/images/pic3747956_t.png",
"minPlayers": 2,
"maxPlayers": 5,
"playingTime": 45,
"isExpansion": false,
"yearPublished": 2012,
"bggRating": 0,
"averageRating": 7.07236,
"rank": 424,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 2952,
"name": "Trivial Pursuit",
"image": "https://cf.geekdo-images.com/images/pic387612.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic387612_t.jpg",
"minPlayers": 2,
"maxPlayers": 24,
"playingTime": 90,
"isExpansion": false,
"yearPublished": 1981,
"bggRating": 0,
"averageRating": 5.20579,
"rank": 14586,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 5894,
"name": "Twister",
"image": "https://cf.geekdo-images.com/images/pic196428.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic196428_t.jpg",
"minPlayers": 2,
"maxPlayers": 4,
"playingTime": 10,
"isExpansion": false,
"yearPublished": 1966,
"bggRating": 0,
"averageRating": 4.56472,
"rank": 14636,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 2223,
"name": "UNO",
"image": "https://cf.geekdo-images.com/images/pic981505.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic981505_t.jpg",
"minPlayers": 2,
"maxPlayers": 10,
"playingTime": 30,
"isExpansion": false,
"yearPublished": 1971,
"bggRating": 0,
"averageRating": 5.34116,
"rank": 14549,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 11517,
"name": "UNO: Elvis Presley",
"image": "https://cf.geekdo-images.com/images/pic46924.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic46924_t.jpg",
"minPlayers": 2,
"maxPlayers": 10,
"playingTime": 15,
"isExpansion": false,
"yearPublished": 2000,
"bggRating": 0,
"averageRating": 5,
"rank": -1,
"numPlays": 0,
"rating": -1,
"owned": false,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
},
{
"gameId": 20100,
"name": "Wits & Wagers",
"image": "https://cf.geekdo-images.com/images/pic521431.jpg",
"thumbnail": "https://cf.geekdo-images.com/images/pic521431_t.jpg",
"minPlayers": 3,
"maxPlayers": 7,
"playingTime": 25,
"isExpansion": false,
"yearPublished": 2005,
"bggRating": 0,
"averageRating": 6.97468,
"rank": 489,
"numPlays": 0,
"rating": -1,
"owned": true,
"preOrdered": false,
"forTrade": false,
"previousOwned": false,
"want": false,
"wantToPlay": false,
"wantToBuy": false,
"wishList": false,
"userComment": ""
}
];

module.exports = bgLibrary;
